version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smrv2-api
    ports:
      - "3000:3000"
      - "9222:9222"
    environment:
      - APP_ENV=${APP_ENV:-development}
      - APP_PORT=3000
      - APP_NAME=smrv2-api
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL:-1}
      - APP_KEY_PASSWORD=${APP_KEY_PASSWORD:-secret}
      - APP_SALT_PASSWORD=${APP_SALT_PASSWORD:-secret}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-smrv2}
      - DB_SSL_MODE=${DB_SSL_MODE:-disable}
      - DB_TIMEZONE=Asia/Jakarta
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_VHOST=/
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_USERNAME=${SMTP_USERNAME:-your-email@gmail.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-your-app-password}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
      - JWT_ACCESS_EXPIRY=${JWT_ACCESS_EXPIRY:-1d}
      - JWT_REFRESH_EXPIRY=${JWT_REFRESH_EXPIRY:-30d}
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - smrv2-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: smrv2-postgres
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-smrv2}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smrv2-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: smrv2-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smrv2-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: smrv2-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - smrv2-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  smrv2-network:
    driver: bridge
