// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "jakueenak@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth": {
            "post": {
                "description": "Login to the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.UsersLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.UsersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh Token",
                "parameters": [
                    {
                        "description": "Refresh Token Request",
                        "name": "refresh_token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.UsersRefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.UserRefreshTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user but sync data from portal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "Register Request",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.UsersRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.UsersRegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schedules": {
            "get": {
                "description": "Get schedules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schedule"
                ],
                "summary": "Get schedules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Study Program",
                        "name": "study_program",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Course Code",
                        "name": "course_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Class Code",
                        "name": "class_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Course Name",
                        "name": "course_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Day of Week",
                        "name": "day_of_week",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Room Number",
                        "name": "room_number",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Semester",
                        "name": "semester",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Lecturer Name",
                        "name": "lecturer_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "course_code",
                            "class_code",
                            "course_name",
                            "credits",
                            "day_of_week",
                            "room_number",
                            "semester",
                            "start_time",
                            "end_time",
                            "lecturer_name"
                        ],
                        "type": "string",
                        "description": "Sort by field",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Sort order",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.Response-array_github_com_savioruz_smrv2-api_internal_dao_model_UserSchedulesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schedules/sync/all": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sync schedules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schedule"
                ],
                "summary": "Sync schedules @admin",
                "parameters": [
                    {
                        "description": "Sync Schedules Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.UserSchedulesSyncRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.Response-string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/schedules": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get user schedules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User Schedules",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "course_code",
                            "class_code",
                            "course_name",
                            "credits",
                            "day_of_week",
                            "room_number",
                            "semester",
                            "start_time",
                            "end_time",
                            "lecturer_name"
                        ],
                        "type": "string",
                        "description": "Sort by field",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Sort order",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.Response-array_github_com_savioruz_smrv2-api_internal_dao_model_UserSchedulesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/schedules/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sync schedule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Sync Schedule",
                "parameters": [
                    {
                        "description": "Sync Schedule Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.UserSchedulesSyncRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.Response-string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "github_com_savioruz_smrv2-api_internal_dao_model.Paging": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "github_com_savioruz_smrv2-api_internal_dao_model.Response-array_github_com_savioruz_smrv2-api_internal_dao_model_UserSchedulesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.UserSchedulesResponse"
                    }
                },
                "error": {
                    "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.Paging"
                }
            }
        },
        "github_com_savioruz_smrv2-api_internal_dao_model.Response-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "error": {
                    "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.ErrorResponse"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_savioruz_smrv2-api_internal_dao_model.Paging"
                }
            }
        },
        "github_com_savioruz_smrv2-api_internal_dao_model.UserRefreshTokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_savioruz_smrv2-api_internal_dao_model.UserSchedulesResponse": {
            "type": "object",
            "properties": {
                "class_code": {
                    "type": "string"
                },
                "course_code": {
                    "type": "string"
                },
                "course_name": {
                    "type": "string"
                },
                "day": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "lecturer": {
                    "type": "string"
                },
                "room_number": {
                    "type": "string"
                },
                "semester": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "study_program": {
                    "type": "string"
                }
            }
        },
        "github_com_savioruz_smrv2-api_internal_dao_model.UserSchedulesSyncRequest": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "boolean"
                }
            }
        },
        "github_com_savioruz_smrv2-api_internal_dao_model.UsersLoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_savioruz_smrv2-api_internal_dao_model.UsersRefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_savioruz_smrv2-api_internal_dao_model.UsersRegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_savioruz_smrv2-api_internal_dao_model.UsersRegisterResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "github_com_savioruz_smrv2-api_internal_dao_model.UsersResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "semester": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "smrv2-api",
	Description:      "This is an auto-generated API Docs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
